spring:
   datasource:
      url: jdbc:p6spy:postgresql://127.0.0.1:5533/EVEDB
      username: DBEVEADM
      password: 'ABcd12#$'
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
         minimum-idle: 5
         maximum-pool-size: 15